### ISSUE TITLE
Length of Panel Title effecting PB Display

### ISSUE THREAD

**Issue by Skritler** [xTVaser/src-twitch-ext#27] opened 2017-11-18 02:41 UTC

**Comment by xTVaser** [comment] 2017-11-18 02:59
Can you provide some additional information?  
* Is there a profile page that I can see the problem?  
* Are times not showing up just in the configuration page or also on the profile
* Can you provide a screenshot of the settings you are trying to use that is causing the problem because I just saved the settings using speedrun.com name `Skritler` and the times appear as expected.

My twitch profile is currently set to display your times and is working ok - https://www.twitch.tv/xtvaser

**Comment by AlphaKR** [comment] 2017-11-18 03:59
I have the same problem, my times have never showed up before. I gave my speedrun.com user name and they just don't show up. In the extension manager and in the twitch panels.
![image](https://user-images.githubusercontent.com/33771552/32976704-e2c507d8-cbea-11e7-9fcb-ec4e234bcc78.png)

**Comment by AlphaKR** [comment] 2017-11-18 04:01
Actually I might have found a fix. 
![image](https://user-images.githubusercontent.com/33771552/32976716-2fe9d296-cbeb-11e7-94ae-eab06664218b.png)
Not sure what caused it, I think it might be the length of the title because when it was Speedrunning Personal Bests it did not show but when it was Speedrunning or any other title it was visable.

**Comment by xTVaser** [comment] 2017-11-18 04:08
@AlphaKR ahhh thanks, you're right i just was able to reproduce with "Speedrunning Personal Bests"  This is probably just a CSS issue where it is overflowing the time information below it. 

I will look into this, it should be an easy fix.  If you would like to use the title `Speedrunning Personal Bests` then a better workaround would be to just decrease the font size until the times show back up
![image](https://user-images.githubusercontent.com/13153231/32976749-1be14224-cbec-11e7-8f40-1d35f5b59c90.png)

@Skritler if you could confirm that your times appear if you shorten the title as well that would be great!

**Comment by AlphaKR** [comment] 2017-11-18 04:21
Ok thanks.

**Comment by xTVaser** [comment] 2017-11-20 23:51
As the title length issue has been resolved and will be in the upcoming release, I am going to close this issue.

@Skritler if your problem is not currently solved by changing the title length / font size, you can re-open this issue.

**Closed as completed by xTVaser** 2017-11-20 23:51 UTC
Labels: Next Version
